import { readFileSync, writeFileSync } from 'fs';

// 1. Remove language switch from landing page
let lp = readFileSync('app/page.tsx', 'utf8');
lp = lp.replace(
  `              <button\n                onClick={() => setLanguage(language === 'de' ? 'en' : 'de')}\n                className="flex items-center gap-1.5 text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide"\n              >\n                <Globe className="w-4 h-4" />\n                {language.toUpperCase()}\n              </button>\n`,
  ''
);
// Also remove unused Globe import if it exists
lp = lp.replace(', Globe', '');
writeFileSync('app/page.tsx', lp, 'utf8');
console.log('Removed language switch from landing page');

// 2. Update FAQ nav to match landing page
let faq = readFileSync('app/faq/page.tsx', 'utf8');
faq = faq.replace(
  `      {/* Nav */}\n      <nav className="border-b border-brand-border/60 bg-white/90 backdrop-blur-lg sticky top-0 z-40">\n        <div className="max-w-4xl mx-auto px-6 h-20 flex items-center justify-between">\n          <Link href="/" className="flex items-center gap-3">\n            <div className="w-9 h-9 bg-brand-beige rounded-xl flex items-center justify-center">\n              <Shield className="w-5 h-5 text-white" />\n            </div>\n            <span className="text-xl font-display font-bold">VERA</span>\n          </Link>\n          <div className="flex items-center gap-6">\n            <Link href="/register" className="btn-primary text-sm">Starten</Link>\n          </div>\n        </div>\n      </nav>`,
  `      {/* Nav */}\n      <nav className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-xl border-b border-brand-border/30">\n        <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-16">\n          <div className="flex justify-between h-20 items-center">\n            <Link href="/" className="flex items-center gap-3 group">\n              <div className="w-28 h-10 relative">\n                <svg className="w-full h-full text-brand-beige" viewBox="0 0 28 10" fill="none"><text x="0" y="9" fontSize="10" fontWeight="bold" fill="currentColor">VERA</text></svg>\n              </div>\n            </Link>\n            <div className="hidden md:flex items-center gap-10">\n              <Link href="/#features" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">Features</Link>\n              <Link href="/#pricing" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">Preise</Link>\n              <Link href="/faq" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">FAQ</Link>\n              <Link href="/blog" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">Blog</Link>\n              <div className="flex items-center gap-6">\n                <Link href="/login" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">Login</Link>\n                <Link href="/register" className="btn-primary shadow-sm shadow-brand-beige/20">Starten</Link>\n              </div>\n            </div>\n          </div>\n        </div>\n      </nav>`
);
writeFileSync('app/faq/page.tsx', faq, 'utf8');
console.log('Updated FAQ nav');

// 3. Update Blog nav to match landing page
let blog = readFileSync('app/blog/page.tsx', 'utf8');
blog = blog.replace(
  `      <nav className="border-b border-brand-border/60 bg-white/90 backdrop-blur-lg sticky top-0 z-40">\n        <div className="max-w-6xl mx-auto px-6 h-20 flex items-center justify-between">\n          <Link href="/" className="flex items-center gap-3">\n            <div className="w-9 h-9 bg-brand-beige rounded-xl flex items-center justify-center">\n              <Shield className="w-5 h-5 text-white" />\n            </div>\n            <span className="text-xl font-display font-bold">VERA</span>\n          </Link>\n          <div className="flex items-center gap-6">\n            <Link href="/faq" className="text-sm text-brand-secondary hover:text-brand-dark">FAQ</Link>\n            <Link href="/register" className="btn-primary text-sm">Starten</Link>\n          </div>\n        </div>\n      </nav>`,
  `      <nav className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-xl border-b border-brand-border/30">\n        <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-16">\n          <div className="flex justify-between h-20 items-center">\n            <Link href="/" className="flex items-center gap-3 group">\n              <div className="w-28 h-10 relative">\n                <svg className="w-full h-full text-brand-beige" viewBox="0 0 28 10" fill="none"><text x="0" y="9" fontSize="10" fontWeight="bold" fill="currentColor">VERA</text></svg>\n              </div>\n            </Link>\n            <div className="hidden md:flex items-center gap-10">\n              <Link href="/#features" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">Features</Link>\n              <Link href="/#pricing" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">Preise</Link>\n              <Link href="/faq" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">FAQ</Link>\n              <Link href="/blog" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">Blog</Link>\n              <div className="flex items-center gap-6">\n                <Link href="/login" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">Login</Link>\n                <Link href="/register" className="btn-primary shadow-sm shadow-brand-beige/20">Starten</Link>\n              </div>\n            </div>\n          </div>\n        </div>\n      </nav>`
);
writeFileSync('app/blog/page.tsx', blog, 'utf8');
console.log('Updated Blog nav');

// 4. Also update blog/[slug] page
let bslug = readFileSync('app/blog/[slug]/page.tsx', 'utf8');
bslug = bslug.replace(
  `      <nav className="border-b border-brand-border/60 bg-white/90 backdrop-blur-lg sticky top-0 z-40">\n        <div className="max-w-4xl mx-auto px-6 h-20 flex items-center justify-between">\n          <Link href="/" className="flex items-center gap-3">\n            <div className="w-9 h-9 bg-brand-beige rounded-xl flex items-center justify-center">\n              <Shield className="w-5 h-5 text-white" />\n            </div>\n            <span className="text-xl font-display font-bold">VERA</span>\n          </Link>\n          <div className="flex items-center gap-6">\n            <Link href="/blog" className="text-sm text-brand-secondary hover:text-brand-dark">Blog</Link>\n            <Link href="/register" className="btn-primary text-sm">Starten</Link>\n          </div>\n        </div>\n      </nav>`,
  `      <nav className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-xl border-b border-brand-border/30">\n        <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-16">\n          <div className="flex justify-between h-20 items-center">\n            <Link href="/" className="flex items-center gap-3 group">\n              <div className="w-28 h-10 relative">\n                <svg className="w-full h-full text-brand-beige" viewBox="0 0 28 10" fill="none"><text x="0" y="9" fontSize="10" fontWeight="bold" fill="currentColor">VERA</text></svg>\n              </div>\n            </Link>\n            <div className="hidden md:flex items-center gap-10">\n              <Link href="/#features" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">Features</Link>\n              <Link href="/#pricing" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">Preise</Link>\n              <Link href="/faq" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">FAQ</Link>\n              <Link href="/blog" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">Blog</Link>\n              <div className="flex items-center gap-6">\n                <Link href="/login" className="text-sm text-brand-secondary hover:text-brand-dark transition-colors tracking-wide">Login</Link>\n                <Link href="/register" className="btn-primary shadow-sm shadow-brand-beige/20">Starten</Link>\n              </div>\n            </div>\n          </div>\n        </div>\n      </nav>`
);
writeFileSync('app/blog/[slug]/page.tsx', bslug, 'utf8');
console.log('Updated Blog/[slug] nav');

console.log('All done!');